---
title: "About"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Our Project 

*Carie Wu (uni: kw3104 ), Rita Wang (uni: ryw2109), Megan Panier (uni: map2365), Minghe Wang (uni: mw3845) and Huiyan Ni (uni: hn2453)*

## Motivation 

Any New Yorker knows the struggle of needing to find a restroom while on the go. We've all had that moment of hesitation before enjoying a large coffee, wondering if we'll make it to the next stop in time. For subway riders, this challenge is amplified by the limited availability of accessible and operational restrooms near stations—a vital service for millions of commuters. Inspired by this shared experience, our project focuses on analyzing restroom accessibility across the NYC subway system. By analyzing public restroom data and subway station characteristics, we aim to uncover trends, highlight underserved areas, and offer data-driven recommendations to enhance this essential infrastructure for all, particularly individuals with disabilities and families.

## Related Work

We were inspired to perform this analysis after discovering public restroom and subway entrance datasets available through [NYC Open Data](https://data.cityofnewyork.us/City-Government/Public-Restrooms/i7jb-7jku/about_data). These data provide detailed information about restroom accessibility, operational status, and geographic locations, as well as subway station characteristics like entrance type and staffing. Given the significant role public restrooms play in urban life—particularly for families, individuals with disabilities, and commuters—we saw an opportunity to explore accessibility disparities across NYC’s subway system. The richness of the data, including spatial coordinates for restrooms and stations, allowed us to integrate geospatial analysis, predictive modeling, and interactive mapping, making it an excellent fit for the visualization and analysis techniques discussed in class.