---
title: "Report"
output: 
  html_document:
    toc: true
    toc_float: true
---

### Data
The data for our project was sourced from [NYC Open Data](https://data.cityofnewyork.us/City-Government/Public-Restrooms/i7jb-7jku/about_data) and the NYC Transit Data that was shared with the p8105 for homework assignment two.


### Data Dictionary
The raw public restroom and train station dataset we utilized can be found [here](https://github.com/816dramaaddict/p8105_restroom_final.github.io/tree/main/Data), and the zip code data we utilized can be found [here](https://github.com/816dramaaddict/p8105_restroom_final.github.io/tree/main/NYC). Our cleaned merged dataset of the public restroom and train station datasets, available on our project [github](https://github.com/816dramaaddict/p8105_restroom_final.github.io/tree/main/Data), has 356 observations. The following are the variables that are used for this project:

* _line_: train station line

* _station_name_: name of the train station

* _station_latitude_: latitude of the train station

* _station_longitude_: longitude of the train station

* _entrance_type_: type of train station entrance (ex: stairs and ramp)

* _staffing_: the level of staff members on site at the train station

* _station_location_: latitude and longitude coordinate of the station

* _facility_name_: location name of the public restroom

* _location_type_: type of location the public restroom is located at

* _restroom_type_: type of restroom

* _restroom_latitude_: latitude of the public restroom

* _restroom_longitude_: longitude of the public restroom

* _restroom_open_: level to which the public restroom is open form (ex: seasonally opened or year round)

* _restroom_accessibility_: level of ADA accessibility of the facility where the public restroom is located

* _restroom_changing_stations_: whether or not a changing table is available in available public restroom, if so, in which stalls

* _restroom_status_: whether or not the restroom is operational

* _zip_shape_: contain the longitude and latitude boundaries of each zip code area in NYC

* _density_: the calculated density of restroom within each zip code

* _gi_star_: the output result of Getis-Ord Gi Analysis, it used to generate the hot spot map

### Exploratory Analysis
In the visualization section, we looked at some characteristics of NYC public restrooms and NYC subway stations. Using plots showing the distribution of restroom location types, restrooms open status, and the combination of these two features, we found that almost 80% public restrooms are located in park and also almost 80% public restrooms remain open year-round. When focusing on their relationship, locations of public restrooms impact their open status significantly. All future open-status restrooms are located in library and all seasonal open-status restrooms are located in park, which may be influenced by architectural planning for the library and climate change for the park in New York. Moreover, the Not Accessible about level of ADA accessibility of restrooms are occupied about 25% in total dataset. It reminds us to improving the implementation of public restrooms.  When analyzing characteristics of NYC subway stations, we found that the majority of subway stations have vending machines and use stairs as their entrance type. However, through the plot concentrating on relationship between entrance type and ADA level, we observed that easement, elevator, escalator and walkway as stations’ entrance are beneficial for people with disabilities, whereas door, ramp and stair as entrance are not. Therefore, we need to improve subway entrance designs to better serve all citizens.

The Hot Spot Analysis (Getis-Ord Gi)* map provides a spatial statistical view of restroom density across ZIP codes in New York City. Significant hot spots (red areas) are observed in Manhattan, indicating clusters of high restroom accessibility. These areas likely reflect regions with concentrated commercial or tourist activity, necessitating a higher density of public restrooms. Neutral areas (light colors) suggest no significant clustering, representing ZIP codes with restroom density levels close to the average. These areas are predominantly in parts of Queens, Brooklyn, and the Bronx. Cold spots (gray areas) or regions with no data are concentrated in Staten Island and other peripheral regions, highlighting gaps in restroom density or missing data requiring further investigation.

The exploratory analysis also focuses on ADA compliance and free crossover availability as key indicators of subway accessibility, recognizing their intuitive relevance in supporting individuals with disabilities, parents with children, and elders, as well as providing convenience during train direction changes. Through visualizations and summary statistics, we uncovered    accessibility patterns and challenges across various stations. To systematically categorize stations based on these and other categorical features, we employed the k-modes clustering technique. This method was chosen for its technical ability to handle non-numeric data and its intuitive capacity to group stations into distinct accessibility levels, allowing us to gain targeted insights into the overall accessibility performance of NYC’s subway system.

### Additional Analysis
Multiple logistic regression was performed to produce a prediction model that predicts the level of ADA accessibility in restrooms based on their features and associated subway station characteristics. Predictors used include restroom location type, restroom type, restroom changing stations, train station ADA features, train station staffing, and train station entrance type. Based on the prediction model, we see that the restroom location, ramp entrance types and partial staff at train stations are highly significant predictors of a public restroom being fully ADA accessible. For public restrooms that are partially ADA accessible, restroom location, ramp entrance types and no staff members at train stations are strong predictors. Variables such as easement entrance type, elevator entrance type, and stairs entrance type for full ADA accessibility have high p-values, indicating weak evidence of their association with a restroom being fully ADA accessible. Potential multicollinearity or insufficient data may have resulted in very large or null statistical values on escalator entrance type and ramp entrance type. When testing the prediction model on the public restroom and train station data, there is an approximate of "73.03%" accuracy, which may be due to outliers, missing data, or unequal distribution of data among different categories of a variable.
  
To further understand the accessibility landscape of NYC subway stations, we employed the k-modes clustering 
algorithm to categorize stations into three distinct accessibility levels based on key features such as ADA 
compliance, free crossover availability, and restroom accessibility metrics. Given the categorical nature of our data, 
k-modes was particularly suitable as it effectively handles non-numeric variables by minimizing the dissimilarity based 
on the modes of clusters. Prior to clustering, we meticulously pre-processed the dataset by addressing missing values and
ensuring that variables like restroom_changing_stations, restroom_status, restroom_accessibility, and 
restroom_open were appropriately formatted for the analysis. The clustering results revealed that 
restroom_accessibility plays a significant role in determining the overall accessibility levels of stations. 
Specifically, high-accessibility stations predominantly feature fully accessible restrooms, whereas medium- and 
low-accessibility stations often lack such amenities or have incomplete restroom accessibility data. This finding was 
supported by our post-clustering analysis, which indicated a strong association between restroom accessibility and 
cluster assignments. Additionally, the uneven distribution of categorical variables across clusters was evident, which 
likely influenced the uniformity of dominant features within each cluster. These formal statistical analyses not only 
validated our initial observations but also highlighted the critical areas where improvements are needed to enhance the 
accessibility of NYC’s subway system.

### Conclusion and Future Policies
The data we present within our project, likely comes as no surprise to any seasoned New Yorker. We’ve all been there, wondering when the next restroom stop will be, debating whether it is wise to drink that cup of coffee…

The issue of restroom availability in New York City is a multifaceted and pressing peril, especially for vulnerable populations such as those who are currently unhoused, people with disabilities, and individuals who menstruate. To address this problem and improve accessibility, several key actions should be taken:

  1.)	The number of public restrooms in NYC needs to be increased. Although costly, this expansion is crucial, as the current provision of public toilets is inadequate. In fact, NYC needs to restore, and surpass, the number of comfort stations it had in the 1930’s [Teizazu et al., 2021]( https://www.semanticscholar.org/paper/%E2%80%9CDo-We-Not-Bleed%E2%80%9D-Sanitation%2C-Menstrual-Management%2C-Teizazu-Sommer/a3d34ff36f11a3c506d187d72d2646e43959a52f). 
  
  2.)	The maintenance, the number of restrooms in service year-round, and the number of restrooms that are accessible, based on ADA standards must be increased. Furthermore, regular maintenance and cleaning schedules should be implemented to ensure that public restrooms remain safe, hygienic, and functional. This is particularly important for public health and to encourage usage [Maroko et al, 2021]( https://pmc.ncbi.nlm.nih.gov/articles/PMC8221515/).  
  
  3.)	Extend hours of operation: to adequately serve the NYC community, public restrooms should be accessible 24/7. This is essential for those who work non-traditional hours or are experiencing homelessness [Teizazu et al., 2021]( https://www.semanticscholar.org/paper/%E2%80%9CDo-We-Not-Bleed%E2%80%9D-Sanitation%2C-Menstrual-Management%2C-Teizazu-Sommer/a3d34ff36f11a3c506d187d72d2646e43959a52f).
  
  4.)	Collaborate with Businesses and Organizations: Partner with local businesses, community organizations, and public institutions to create a network of accessible restrooms. This could involve incentives for businesses that make their restrooms available to the public.

These measures, although certainly not exhaustive, could can significantly improve restroom availability and accessibility for all in NYC, including those living with disabilities. Incorporating some or all of these approaches would address the current inadequacies in public sanitation infrastructure and help support the health, dignity, and inclusion of all community members.

The lack of publicly available restrooms in NYC is a recognized public health issue, with government officials acknowledging the problem and [initiating measures] (https://www.nyc.gov/office-of-the-mayor/news/441-24/mayor-adams-launches-ur-luck-new-effort-make-nyc-public-restrooms-more-accessible-#/0) to address this crisis. 

The New York City Council's investigation, and [subsequent report]( https://council.nyc.gov/press/2024/09/05/2689/), of 102 public restrooms in city parks revealed that two-thirds were either closed or had significant health and safety issues. The report, titled "Nature's Call," highlighted widespread problems including unsanitary conditions, lack of basic amenities, and inadequate maintenance, underscoring the urgent need for improved funding and management of public restroom facilities in NYC parks.

### References
  1. [https://data.cityofnewyork.us/City-Government/Public-Restrooms/i7jb-7jku](https://data.cityofnewyork.us/City-Government/Public-Restrooms/i7jb-7jku)
  2. [https://data.cityofnewyork.us/Health/Modified-Zip-Code-Tabulation-Areas-MODZCTA-/pri4-ifjk/about_data](https://data.cityofnewyork.us/Health/Modified-Zip-Code-Tabulation-Areas-MODZCTA-/pri4-ifjk/about_data)
  3. Fozouni, L., Buchheit, B., Walley, A. Y., Testa, M., & Chatterjee, A. (2019). Public restrooms and the opioid epidemic. American Journal of Public Health, 109(8), 1061-1062.
  4. Kang, S. (2021). Female restrooms in the tourist destination: How the socio-spatial conditions of public toilets influence women's perception of safety. Tourism Management, 86, 104343.
  5. Teizazu, H., Sommer, M., Gruer, C., Giffen, D., Davis, L., Frumin, R., & Hopper, K. (2021). “Do We Not Bleed?” Sanitation, Menstrual Management, and Homelessness in the Time of COVID. Columbia Journal of Gender and Law.
  6. Maroko, A. R., Hopper, K., Gruer, C., Jaffe, M., Zhen, E., & Sommer, M. (2021). Public restrooms, periods, and people experiencing homelessness: An assessment of public toilets in high needs areas of Manhattan, New York. PloS one, 16(6), e0252946. https://doi.org/10.1371/journal.pone.0252946
